// content-public.js — treść publicznego bota FAQ (przestrzeń `public`).
//
// Wydzielone z worker.js 19.08.2026: treść to ponad połowa wagi tamtego pliku,
// a zadanie dotyczące logiki nigdy jej nie potrzebuje. Import rozwiązuje
// bundler (esbuild w wranglerze) i skleja wszystko z powrotem w jeden plik
// przy deployu — konfiguracja Workera i rozmiar uploadu bez zmian.
//
// PO KAŻDEJ ZMIANIE TEJ TABLICY: /reindex?key=…&space=public — bez tego indeks
// nie widzi poprawki. Zapis do Vectorize jest asynchroniczny, więc odczekaj.

// ============================================================
// TREŚĆ FIRMOWA — 53 fragmenty, oparte o realne przepisy (KC, WT2021,
// KSeF, Czyste Powietrze) przepisane na fikcyjną firmę BudMax.
// ============================================================
export const CHUNKS = [
  // --- Kontakt i obsługa klienta ---
  { id: "c01", title: "Godziny pracy i kontakt", text: "Biuro czynne jest od poniedziałku do piątku w godzinach 7:00–16:00. Kontakt telefoniczny: sekretariat, e-mail: biuro@budmax.przyklad.pl. W pilnych sprawach związanych z realizowaną budową klient kontaktuje się bezpośrednio z kierownikiem budowy." },
  { id: "c02", title: "Umawianie wizji lokalnej", text: "Wizję lokalną umawia się telefonicznie lub mailowo, zwykle z wyprzedzeniem 3-5 dni roboczych. Spotkanie trwa około godziny i obejmuje ocenę działki, dostępu, warunków gruntowych oraz wstępne omówienie oczekiwań klienta." },
  { id: "c03", title: "Kanały zgłaszania spraw", text: "Sprawy pilne (bezpieczeństwo, awarie na budowie) zgłasza się telefonicznie do kierownika budowy. Sprawy niepilne (pytania, zmiany, dokumenty) przez e-mail lub formularz na stronie — czas odpowiedzi do 2 dni roboczych." },
  { id: "c04", title: "RODO i ochrona danych klienta", text: "Dane osobowe klientów przetwarzane są wyłącznie w celu realizacji umowy, zgodnie z RODO. Administratorem danych jest BudMax Sp. z o.o. Dane nie są przekazywane podmiotom trzecim poza wykonawcami niezbędnymi do realizacji budowy (podwykonawcy, bank przy kredycie). Klient ma prawo wglądu, poprawy i żądania usunięcia danych po zakończeniu okresu przechowywania wymaganego przepisami podatkowymi." },

  // --- Oferta i wycena ---
  { id: "c05", title: "Zakres oferowanych usług", text: "Budowa domów jednorodzinnych w stanie surowym i deweloperskim, remonty kompleksowe, nadzór budowlany, usługi projektowe we współpracy z pracownią architektoniczną, adaptacje projektów gotowych, doradztwo przy wyborze technologii." },
  { id: "c06", title: "Proces przygotowania wyceny", text: "Wstępna wycena jest bezpłatna, gotowa w 5 dni roboczych od wizji lokalnej. Zależy od zakresu prac, materiałów i terminu. Ostateczny kosztorys może różnić się od wstępnego o maksymalnie 10%, chyba że klient zmieni zakres w trakcie." },
  { id: "c07", title: "Co wchodzi w skład kosztorysu", text: "Kosztorys obejmuje materiały budowlane, robociznę, wynajem sprzętu ciężkiego oraz koszty utylizacji odpadów budowlanych. Nie obejmuje projektu architektonicznego, opłat urzędowych ani wyposażenia ruchomego (meble, AGD)." },
  { id: "c08", title: "Stan surowy otwarty, zamknięty, deweloperski", text: "Stan surowy otwarty: fundamenty, ściany, strop, bez dachu i okien. Stan surowy zamknięty: dodatkowo dach, okna, drzwi zewnętrzne. Stan deweloperski: dodatkowo tynki, instalacje, wylewki — gotowe do wykończenia przez klienta." },
  { id: "c09", title: "Umowa o roboty budowlane — co zawiera", text: "Zgodnie z art. 647 Kodeksu cywilnego umowa określa zobowiązanie wykonawcy do oddania obiektu zgodnie z projektem, oraz obowiązki inwestora: przekazanie terenu budowy, dostarczenie projektu i zapłatę wynagrodzenia. Nasza umowa dodatkowo precyzuje harmonogram, standard materiałów, zasady odbiorów częściowych i warunki wprowadzania zmian w trakcie realizacji." },

  // --- Etapy i harmonogram ---
  { id: "c10", title: "Etapy realizacji projektu", text: "Współpraca przebiega w pięciu etapach: spotkanie i wizja lokalna, wycena i umowa, harmonogram, realizacja z odbiorami częściowymi po każdym etapie, odbiór końcowy z przekazaniem dokumentacji powykonawczej." },
  { id: "c11", title: "Czas realizacji fundamentów", text: "Wykonanie fundamentów dla typowego domu 120-160 m² trwa 2-3 tygodnie, w zależności od warunków gruntowych i pogody. Obejmuje wykop, izolację, zbrojenie i zalanie ław lub płyty fundamentowej." },
  { id: "c12", title: "Czas realizacji stanu surowego", text: "Stan surowy otwarty realizowany jest zwykle w 6-8 tygodni. Stan surowy zamknięty (dodatkowo dach, okna, drzwi) wymaga kolejnych 3-4 tygodni po zamknięciu stanu otwartego." },
  { id: "c13", title: "Czas instalacji i wykończeń", text: "Instalacje (elektryczne, hydrauliczne, wentylacyjne) i wykończenia zajmują 8-12 tygodni, zależnie od standardu. Łączny czas budowy domu w stanie deweloperskim to zwykle 6-9 miesięcy od wejścia na plac budowy." },
  { id: "c14", title: "Co wydłuża harmonogram budowy", text: "Najczęstsze przyczyny opóźnień: niekorzystne warunki pogodowe zimą, zmiany zakresu prac zgłoszone w trakcie realizacji, opóźnienia w dostawach materiałów specjalnych oraz nieprzewidziane warunki gruntowe." },
  { id: "c15", title: "Dziennik budowy — dokument formalny", text: "Dziennik budowy jest urzędowym dokumentem prowadzonym od dnia rozpoczęcia robót, w którym kierownik budowy odnotowuje przebieg prac, ważne zdarzenia i odbiory. Prowadzimy go zgodnie z wymogami prawa budowlanego i przekazujemy klientowi wraz z dokumentacją powykonawczą po zakończeniu inwestycji." },

  // --- Materiały i technologia ---
  { id: "c16", title: "Standardy wykończenia", text: "Trzy standardy: ekonomiczny, standardowy, podwyższony — różnią się klasą materiałów wykończeniowych (płytki, armatura, stolarka). Materiały konstrukcyjne są tej samej, sprawdzonej jakości niezależnie od wybranego standardu." },
  { id: "c17", title: "Technologia murowana, szkieletowa, prefabrykowana", text: "Technologia murowana: najbardziej uniwersalna, dłuższy czas budowy, wysoka akumulacja ciepła. Szkieletowa drewniana: szybsza realizacja, dobra izolacyjność. Prefabrykowana: najkrótszy czas budowy, ograniczona możliwość zmian w trakcie." },
  { id: "c18", title: "Materiały konstrukcyjne", text: "Do prac konstrukcyjnych używamy betonu towarowego z certyfikowanych węzłów betoniarskich, stali zbrojeniowej z atestami, bloczków ceramicznych lub silikatowych oraz więźby dachowej z drewna klasy C24." },
  { id: "c19", title: "Materiały własne klienta", text: "Klient może zaproponować własnych dostawców materiałów wykończeniowych. Wymaga to zgłoszenia na etapie kosztorysowania i akceptacji — wpływa na harmonogram dostaw i może wymagać korekty terminu realizacji." },

  // --- Formalności i prawo ---
  { id: "c20", title: "Pomoc w formalnościach budowlanych", text: "Pomagamy skompletować dokumentację do zgłoszenia budowy lub pozwolenia, we współpracy z biurem projektowym. Usługa jest płatna osobno, wyceniana według stopnia skomplikowania sprawy." },
  { id: "c21", title: "Zgłoszenie a pozwolenie na budowę", text: "Zgłoszenie budowy wystarcza dla domów jednorodzinnych o określonej powierzchni i przeznaczeniu, jeśli nie wymagają oceny oddziaływania na środowisko. Pozwolenie na budowę jest wymagane w pozostałych przypadkach — czas oczekiwania jest dłuższy." },
  { id: "c22", title: "Warunki zabudowy i decyzja środowiskowa", text: "Dla działek bez miejscowego planu zagospodarowania konieczne jest uzyskanie warunków zabudowy. W niektórych lokalizacjach wymagana jest też decyzja środowiskowa — pomagamy ustalić, czy dotyczy to konkretnej działki." },
  { id: "c23", title: "Geodezja i tyczenie budynku", text: "Przed rozpoczęciem prac ziemnych zlecamy uprawnionemu geodecie tyczenie budynku, czyli wyznaczenie jego dokładnego położenia na działce zgodnie z projektem. Po zakończeniu budowy geodeta wykonuje inwentaryzację powykonawczą, niezbędną do zgłoszenia zakończenia budowy." },
  { id: "c24", title: "Odbiór robót od wykonawcy — procedura formalna", text: "Odbiór częściowy i końcowy potwierdzany jest protokołem podpisanym przez klienta i kierownika budowy, wskazującym ewentualne usterki do poprawy w wyznaczonym terminie. Podpisanie protokołu odbioru bez zastrzeżeń jest podstawą do wystawienia faktury za dany etap." },
  { id: "c25", title: "Odbiory urzędowe po budowie", text: "Po zakończeniu budowy klient zgłasza zakończenie do nadzoru budowlanego, dołączając dziennik budowy, atesty materiałów i schematy instalacji, które przekazujemy w komplecie dokumentacji powykonawczej." },

  // --- Finanse, płatności, dotacje ---
  { id: "c26", title: "Harmonogram płatności", text: "Rozliczenie w transzach powiązanych z etapami realizacji, na podstawie faktur VAT po każdym odbiorze częściowym. Pierwsza wpłata (zaliczka) wynosi standardowo 10% wartości kontraktu, płatna przy podpisaniu umowy." },
  { id: "c27", title: "Kredyt budowlany i współpraca z bankami", text: "Współpracujemy z kilkoma bankami przy kredytach budowlanych. Na życzenie klienta przygotowujemy dokumenty (kosztorys, harmonogram, umowa) wymagane przez bank do uruchamiania kolejnych transz kredytu." },
  { id: "c28", title: "Faktury i rozliczenia przez KSeF", text: "Jak wystawiamy faktury i jak wygląda rozliczenie dokumentów: od 1 lutego 2026 roku obowiązkowy KSeF (Krajowy System e-Faktur) objął duże firmy, a od 1 kwietnia 2026 roku obejmuje pozostałych przedsiębiorców, w tym BudMax. Wszystkie nasze faktury VAT dla firm wystawiane są ustrukturyzowanie przez KSeF — klient biznesowy otrzymuje fakturę z systemu Krajowej Administracji Skarbowej z nadanym numerem KSeF." },
  { id: "c29", title: "Stawki VAT w budownictwie mieszkaniowym", text: "Dla budownictwa mieszkaniowego objętego społecznym programem mieszkaniowym stosujemy obniżoną stawkę VAT zgodnie z obowiązującymi przepisami. Dokładną stawkę potwierdzamy indywidualnie przy wycenie, w zależności od metrażu i przeznaczenia." },
  { id: "c30", title: "Program Czyste Powietrze — dofinansowanie", text: "Pomagamy klientom skorzystać z rządowego programu Czyste Powietrze, który w zależności od progu dochodowego oferuje dofinansowanie do 66 000 zł, 99 000 zł lub nawet 136 200 zł na termomodernizację i wymianę źródła ciepła, a przy kompleksowej termomodernizacji z gruntową pompą ciepła — do 170 100 zł. Program wymaga obowiązkowego audytu energetycznego przed złożeniem wniosku." },
  { id: "c31", title: "Inne dotacje i ulgi termomodernizacyjne", text: "Poza programem Czyste Powietrze doradzamy też w zakresie ulgi termomodernizacyjnej w rozliczeniu PIT oraz lokalnych programów dopłat, jeśli są dostępne w danej gminie. Ostateczną kwalifikację i wniosek klient składa samodzielnie lub z pomocą doradcy finansowego." },

  // --- Bezpieczeństwo i ubezpieczenie ---
  { id: "c32", title: "Ubezpieczenie budowy", text: "Każda budowa objęta jest ubezpieczeniem OC działalności budowlanej oraz ubezpieczeniem budowy w trakcie realizacji na sumę odpowiadającą wartości kontraktu. Kopię polisy przekazujemy klientowi przy podpisaniu umowy." },
  { id: "c33", title: "Zabezpieczenie terenu budowy", text: "Teren budowy jest ogrodzony i oznakowany zgodnie z przepisami BHP przez cały okres realizacji. Dostęp osób postronnych jest ograniczony, a materiały i sprzęt przechowywane są w zamykanych kontenerach." },
  { id: "c34", title: "BHP i szkolenia pracowników", text: "Każda osoba na budowie nosi kask, obuwie z podnoskiem i kamizelkę odblaskową. Praca na wysokości powyżej 2 metrów wymaga szelek i asekuracji. Szkolenie BHP jest obowiązkowe i odnawiane co 12 miesięcy." },
  { id: "c35", title: "Wjazd na budowę i logistyka dostaw", text: "Dostawy materiałów i sprzętu koordynowane są przez kierownika budowy, zwykle w godzinach 7:00-15:00 w dni robocze. Klient jest informowany z wyprzedzeniem o większych dostawach (beton, więźba dachowa), które mogą czasowo ograniczyć dojazd do działki." },
  { id: "c36", title: "Media i przyłącza (prąd, woda, kanalizacja)", text: "Organizujemy wykonanie przyłączy energetycznych, wodociągowych i kanalizacyjnych we współpracy z lokalnymi dostawcami mediów. Czas oczekiwania na przyłącze energetyczne zależy od operatora sieci i zwykle wynosi od kilku tygodni do kilku miesięcy — warto złożyć wniosek jak najwcześniej, równolegle z formalnościami budowlanymi." },

  // --- Zespół i realizacja ---
  { id: "c37", title: "Własny zespół i podwykonawcy", text: "Prace konstrukcyjne wykonuje stały zespół zatrudniony na umowę o pracę. Do prac instalacyjnych (elektryka, hydraulika, wentylacja) współpracujemy ze sprawdzonymi podwykonawcami z wieloletnimi umowami ramowymi." },
  { id: "c38", title: "Rola kierownika budowy", text: "Kierownik budowy nadzoruje realizację, odpowiada za zgodność z projektem i przepisami, prowadzi dziennik budowy oraz jest głównym punktem kontaktu dla klienta w sprawach bieżących związanych z postępem prac na miejscu." },
  { id: "c39", title: "Raportowanie postępu klientowi", text: "Klient jest informowany o postępach standardowo raz w tygodniu przez kierownika budowy — telefonicznie, mailowo lub podczas wizyty na budowie, w zależności od preferencji ustalonych na starcie współpracy." },

  // --- Wykończenia wnętrz ---
  { id: "c40", title: "Wykończenie wnętrz — zakres usług", text: "Oferujemy pełne wykończenie wnętrz: tynki, malowanie, podłogi, glazurę, biały montaż, zabudowy meblowe na zamówienie. Zakres i standard ustalany jest indywidualnie na etapie kosztorysowania." },
  { id: "c41", title: "Łazienki i kuchnie pod klucz", text: "Realizujemy łazienki i kuchnie w formule pod klucz, od hydrauliki i elektryki po montaż płytek, armatury i mebli. Czas realizacji jednego pomieszczenia to zwykle 2-4 tygodnie, zależnie od zakresu." },
  { id: "c53", title: "Elewacje i docieplenia budynku — wykonanie", text: "Czy wykonujemy elewacje i docieplenia budynku: tak, elewacje i docieplenia wykonujemy jako część prac wykończeniowych przy budowie oraz jako osobne zlecenie przy remontach. Zakres obejmuje tynki zewnętrzne, docieplenie styropianem lub wełną oraz wykończenie elewacji. Zakres i standard ustalany jest indywidualnie na etapie kosztorysowania. To usługa dotycząca wykonania elewacji — co innego niż konserwacja elewacji w ramach serwisu pogwarancyjnego, która dotyczy budynków już przez nas wykonanych (patrz osobny fragment: Serwis pogwarancyjny)." },

  // --- Otoczenie budynku: ogrody i ogrodzenia rozdzielone wyraźnie ---
  { id: "c42", title: "Ogrody i tereny zielone — pielęgnacja krajobrazu", text: "Czy zakładamy ogrody i zieleń wokół domu: po zakończeniu budowy oferujemy podstawowe zagospodarowanie terenu zielonego: niwelację gruntu, obsianie trawnikiem, nasadzenia roślin i zieleni. Bardziej rozbudowane projekty ogrodowe realizujemy we współpracy z zewnętrznymi architektami krajobrazu. To usługa dotycząca roślinności i zieleni — nie obejmuje ogrodzeń ani utwardzonych powierzchni (patrz osobny fragment: Ogrodzenia, bramy i podjazdy)." },
  { id: "c43", title: "Ogrodzenia, bramy i podjazdy — infrastruktura działki", text: "Wykonujemy ogrodzenia (panelowe, murowane, drewniane), bramy wjazdowe oraz podjazdy i place utwardzone kostką brukową lub betonem. Wyceniane są osobno od budowy głównej, na podstawie odrębnego kosztorysu. To usługa dotycząca infrastruktury i ogrodzeń działki — nie obejmuje zieleni ani nasadzeń (patrz osobny fragment: Ogrody i tereny zielone)." },

  // --- Gwarancja i rękojmia, poprawnie rozdzielone prawnie ---
  { id: "c44", title: "Rękojmia na roboty budowlane — prawo ustawowe", text: "Zgodnie z art. 568 §1 Kodeksu cywilnego inwestorowi przysługuje ustawowa rękojmia za wady obiektu budowlanego przez 5 lat od dnia odbioru, a przy umowach obejmujących wyłącznie remont lub wykończenie — przez 2 lata. Rękojmia obowiązuje z mocy samego prawa, niezależnie od tego, czy BudMax dodatkowo udzieli gwarancji. W jej ramach klient może żądać usunięcia wady, obniżenia wynagrodzenia lub, w skrajnych przypadkach, odstąpienia od umowy." },
  { id: "c45", title: "Gwarancja umowna — dodatkowa ochrona", text: "Niezależnie od ustawowej rękojmi, BudMax udziela dodatkowej gwarancji umownej na wykonane prace, potwierdzonej kartą gwarancyjną przekazywaną przy odbiorze. Gwarancja nie obejmuje uszkodzeń powstałych w wyniku nieprawidłowego użytkowania obiektu, samowolnych zmian konstrukcyjnych wykonanych przez inne firmy po odbiorze, ani zdarzeń losowych." },
  { id: "c46", title: "Różnica między rękojmią a gwarancją", text: "Rękojmia to prawo ustawowe, obowiązujące zawsze i niezależnie od woli wykonawcy (5 lat na roboty budowlane, 2 lata na remont). Gwarancja to dodatkowe, dobrowolne zobowiązanie BudMax, opisane w karcie gwarancyjnej. Klient może skorzystać najpierw z gwarancji, a jeśli sprawa nie zostanie załatwiona — skorzystać z rękojmi, która daje szersze uprawnienia." },
  { id: "c47", title: "Proces zgłaszania reklamacji", text: "Co zrobić, gdy po odbiorze pojawi się usterka lub wada: reklamację zgłasza się telefonicznie, mailowo lub przez formularz na stronie. Termin rozpatrzenia to 14 dni roboczych. Usterki zagrażające bezpieczeństwu są obsługiwane priorytetowo, w ciągu 48 godzin od zgłoszenia." },
  { id: "c48", title: "Serwis pogwarancyjny", text: "Po zakończeniu okresu gwarancji oferujemy odpłatny serwis pogwarancyjny: przeglądy instalacji, drobne naprawy, konserwację elewacji i dachu. Wycena serwisu ustalana jest indywidualnie po zgłoszeniu. To utrzymanie obiektów już przez nas wykonanych, po okresie gwarancji — nie obejmuje wykonania nowej elewacji ani docieplenia budynku (patrz osobny fragment: Elewacje i docieplenia budynku)." },

  // --- Standard energetyczny, oparty o realne wartości WT2021 ---
  { id: "c49", title: "Standard energetyczny budynków — wymagania WT2021", text: "Wszystkie realizowane przez nas domy spełniają obowiązujące od 31 grudnia 2020 roku warunki techniczne WT2021: współczynnik przenikania ciepła dachu nie przekracza 0,15 W/(m²K), ścian zewnętrznych 0,20 W/(m²K), a podłogi na gruncie 0,30 W/(m²K). W praktyce oznacza to zwykle 25-35 cm izolacji dachu i 15-20 cm izolacji ścian, w zależności od materiału." },
  { id: "c50", title: "Fotowoltaika i pompy ciepła", text: "Przygotowujemy instalację pod montaż fotowoltaiki i pompy ciepła już na etapie budowy (odpowiednie okablowanie, miejsce na urządzenia). Sam montaż realizujemy we współpracy z certyfikowanymi partnerami technologicznymi, dobierając urządzenia kwalifikujące się do dofinansowania z programu Czyste Powietrze." },

  // --- Zmiany i obszar działania ---
  { id: "c51", title: "Zmiany w trakcie budowy", text: "Zmiana zakresu prac wymaga pisemnego aneksu do umowy z aktualizacją kosztorysu. Zmiany zgłoszone przed rozpoczęciem danego etapu nie generują dodatkowych kosztów administracyjnych, zgłoszone później — mogą generować." },
  { id: "c52", title: "Obszar działania i dojazd", text: "Gdzie działamy i gdzie realizujemy budowy: na terenie województwa zachodniopomorskiego, głównie w okolicach Szczecina i Kołobrzegu. Obsługujemy klientów z tego regionu. Dla budów powyżej 60 km od siedziby doliczamy ryczałt transportowy ustalany indywidualnie." },
];
